// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/moqwordsearch.proto

package wsproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchItem struct {
	Term                 string   `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	SearchCount          int64    `protobuf:"varint,2,opt,name=search_count,json=searchCount,proto3" json:"search_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchItem) Reset()         { *m = SearchItem{} }
func (m *SearchItem) String() string { return proto.CompactTextString(m) }
func (*SearchItem) ProtoMessage()    {}
func (*SearchItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4c2990c44e215f, []int{0}
}

func (m *SearchItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchItem.Unmarshal(m, b)
}
func (m *SearchItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchItem.Marshal(b, m, deterministic)
}
func (m *SearchItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchItem.Merge(m, src)
}
func (m *SearchItem) XXX_Size() int {
	return xxx_messageInfo_SearchItem.Size(m)
}
func (m *SearchItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchItem.DiscardUnknown(m)
}

var xxx_messageInfo_SearchItem proto.InternalMessageInfo

func (m *SearchItem) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *SearchItem) GetSearchCount() int64 {
	if m != nil {
		return m.SearchCount
	}
	return 0
}

type SingleWordRequest struct {
	Term                 string   `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleWordRequest) Reset()         { *m = SingleWordRequest{} }
func (m *SingleWordRequest) String() string { return proto.CompactTextString(m) }
func (*SingleWordRequest) ProtoMessage()    {}
func (*SingleWordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4c2990c44e215f, []int{1}
}

func (m *SingleWordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleWordRequest.Unmarshal(m, b)
}
func (m *SingleWordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleWordRequest.Marshal(b, m, deterministic)
}
func (m *SingleWordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleWordRequest.Merge(m, src)
}
func (m *SingleWordRequest) XXX_Size() int {
	return xxx_messageInfo_SingleWordRequest.Size(m)
}
func (m *SingleWordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleWordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SingleWordRequest proto.InternalMessageInfo

func (m *SingleWordRequest) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

type SingleWordResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleWordResponse) Reset()         { *m = SingleWordResponse{} }
func (m *SingleWordResponse) String() string { return proto.CompactTextString(m) }
func (*SingleWordResponse) ProtoMessage()    {}
func (*SingleWordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4c2990c44e215f, []int{2}
}

func (m *SingleWordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleWordResponse.Unmarshal(m, b)
}
func (m *SingleWordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleWordResponse.Marshal(b, m, deterministic)
}
func (m *SingleWordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleWordResponse.Merge(m, src)
}
func (m *SingleWordResponse) XXX_Size() int {
	return xxx_messageInfo_SingleWordResponse.Size(m)
}
func (m *SingleWordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleWordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SingleWordResponse proto.InternalMessageInfo

func (m *SingleWordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TopFiveRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopFiveRequest) Reset()         { *m = TopFiveRequest{} }
func (m *TopFiveRequest) String() string { return proto.CompactTextString(m) }
func (*TopFiveRequest) ProtoMessage()    {}
func (*TopFiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4c2990c44e215f, []int{3}
}

func (m *TopFiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopFiveRequest.Unmarshal(m, b)
}
func (m *TopFiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopFiveRequest.Marshal(b, m, deterministic)
}
func (m *TopFiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopFiveRequest.Merge(m, src)
}
func (m *TopFiveRequest) XXX_Size() int {
	return xxx_messageInfo_TopFiveRequest.Size(m)
}
func (m *TopFiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopFiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopFiveRequest proto.InternalMessageInfo

type TopFiveResponse struct {
	TopFive              []*SearchItem `protobuf:"bytes,1,rep,name=top_five,json=topFive,proto3" json:"top_five,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TopFiveResponse) Reset()         { *m = TopFiveResponse{} }
func (m *TopFiveResponse) String() string { return proto.CompactTextString(m) }
func (*TopFiveResponse) ProtoMessage()    {}
func (*TopFiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4c2990c44e215f, []int{4}
}

func (m *TopFiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopFiveResponse.Unmarshal(m, b)
}
func (m *TopFiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopFiveResponse.Marshal(b, m, deterministic)
}
func (m *TopFiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopFiveResponse.Merge(m, src)
}
func (m *TopFiveResponse) XXX_Size() int {
	return xxx_messageInfo_TopFiveResponse.Size(m)
}
func (m *TopFiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopFiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopFiveResponse proto.InternalMessageInfo

func (m *TopFiveResponse) GetTopFive() []*SearchItem {
	if m != nil {
		return m.TopFive
	}
	return nil
}

type UpdateWordListRequest struct {
	Term                 string   `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWordListRequest) Reset()         { *m = UpdateWordListRequest{} }
func (m *UpdateWordListRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateWordListRequest) ProtoMessage()    {}
func (*UpdateWordListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4c2990c44e215f, []int{5}
}

func (m *UpdateWordListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWordListRequest.Unmarshal(m, b)
}
func (m *UpdateWordListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWordListRequest.Marshal(b, m, deterministic)
}
func (m *UpdateWordListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWordListRequest.Merge(m, src)
}
func (m *UpdateWordListRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateWordListRequest.Size(m)
}
func (m *UpdateWordListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWordListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWordListRequest proto.InternalMessageInfo

func (m *UpdateWordListRequest) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

type UpdateWordListResponse struct {
	Message              string        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	WordList             []*SearchItem `protobuf:"bytes,2,rep,name=word_list,json=wordList,proto3" json:"word_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateWordListResponse) Reset()         { *m = UpdateWordListResponse{} }
func (m *UpdateWordListResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateWordListResponse) ProtoMessage()    {}
func (*UpdateWordListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d4c2990c44e215f, []int{6}
}

func (m *UpdateWordListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWordListResponse.Unmarshal(m, b)
}
func (m *UpdateWordListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWordListResponse.Marshal(b, m, deterministic)
}
func (m *UpdateWordListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWordListResponse.Merge(m, src)
}
func (m *UpdateWordListResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateWordListResponse.Size(m)
}
func (m *UpdateWordListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWordListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWordListResponse proto.InternalMessageInfo

func (m *UpdateWordListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateWordListResponse) GetWordList() []*SearchItem {
	if m != nil {
		return m.WordList
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchItem)(nil), "wsproto.SearchItem")
	proto.RegisterType((*SingleWordRequest)(nil), "wsproto.SingleWordRequest")
	proto.RegisterType((*SingleWordResponse)(nil), "wsproto.SingleWordResponse")
	proto.RegisterType((*TopFiveRequest)(nil), "wsproto.TopFiveRequest")
	proto.RegisterType((*TopFiveResponse)(nil), "wsproto.TopFiveResponse")
	proto.RegisterType((*UpdateWordListRequest)(nil), "wsproto.UpdateWordListRequest")
	proto.RegisterType((*UpdateWordListResponse)(nil), "wsproto.UpdateWordListResponse")
}

func init() {
	proto.RegisterFile("proto/moqwordsearch.proto", fileDescriptor_9d4c2990c44e215f)
}

var fileDescriptor_9d4c2990c44e215f = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcd, 0xae, 0xd2, 0x40,
	0x14, 0xc7, 0x03, 0x18, 0x81, 0x03, 0x22, 0x0c, 0x7e, 0x94, 0x6a, 0x14, 0x67, 0x23, 0x89, 0xa1,
	0x25, 0xb8, 0x74, 0xa5, 0x24, 0x26, 0x26, 0x86, 0x45, 0xd1, 0x68, 0x5c, 0xd8, 0x14, 0x3a, 0x96,
	0x49, 0xda, 0xce, 0xd0, 0x99, 0xc2, 0xc2, 0xb8, 0xf1, 0x15, 0x7c, 0x1c, 0x1f, 0xc3, 0x57, 0xf0,
	0x41, 0xcc, 0x4c, 0x47, 0x0a, 0x5c, 0xb8, 0x77, 0xc5, 0x70, 0x3e, 0x7e, 0xe7, 0x3f, 0xff, 0x39,
	0x85, 0x01, 0xcf, 0x98, 0x64, 0x6e, 0xc2, 0x36, 0x3b, 0x96, 0x85, 0x82, 0x04, 0xd9, 0x6a, 0xed,
	0xe8, 0x18, 0xaa, 0xef, 0x84, 0x3e, 0xd8, 0x8f, 0x23, 0xc6, 0xa2, 0x98, 0xb8, 0x01, 0xa7, 0x6e,
	0x90, 0xa6, 0x4c, 0x06, 0x92, 0xb2, 0x54, 0x14, 0x65, 0x78, 0x06, 0xb0, 0xd0, 0x6d, 0xef, 0x24,
	0x49, 0x10, 0x82, 0x5b, 0x92, 0x64, 0x89, 0x55, 0x19, 0x56, 0x46, 0x4d, 0x4f, 0x9f, 0xd1, 0x33,
	0x68, 0x17, 0x60, 0x7f, 0xc5, 0xf2, 0x54, 0x5a, 0xd5, 0x61, 0x65, 0x54, 0xf3, 0x5a, 0x45, 0x6c,
	0xa6, 0x42, 0xf8, 0x39, 0xf4, 0x16, 0x34, 0x8d, 0x62, 0xf2, 0x89, 0x65, 0xa1, 0x47, 0x36, 0x39,
	0x11, 0xf2, 0x1c, 0x0b, 0x3b, 0x80, 0x0e, 0x0b, 0x05, 0x67, 0xa9, 0x20, 0xc8, 0x82, 0x7a, 0x42,
	0x84, 0x08, 0x22, 0x62, 0x8a, 0xff, 0xff, 0xc5, 0x5d, 0xe8, 0x7c, 0x60, 0xfc, 0x2d, 0xdd, 0x12,
	0x43, 0xc5, 0xaf, 0xe1, 0xee, 0x3e, 0x62, 0xda, 0x1d, 0x68, 0x48, 0xc6, 0xfd, 0x6f, 0x74, 0xab,
	0xfa, 0x6b, 0xa3, 0xd6, 0xb4, 0xef, 0x98, 0xcb, 0x3b, 0xe5, 0xdd, 0xbc, 0xba, 0x2c, 0xfa, 0xf0,
	0x0b, 0xb8, 0xff, 0x91, 0x87, 0x81, 0xd4, 0x22, 0xde, 0x53, 0x21, 0xaf, 0x53, 0x1c, 0xc2, 0x83,
	0xd3, 0xe2, 0x9b, 0x54, 0xa3, 0x09, 0x34, 0xd5, 0x73, 0xf8, 0x31, 0x15, 0xca, 0xae, 0x8b, 0x8a,
	0x1a, 0x3b, 0xc3, 0x9c, 0xfe, 0xae, 0x02, 0xa8, 0x01, 0x45, 0x12, 0xf9, 0xd0, 0x2d, 0x6d, 0x32,
	0x31, 0xbb, 0x24, 0x9c, 0x5a, 0x6d, 0x3f, 0x3a, 0x9b, 0x2b, 0x74, 0x62, 0xf4, 0xf3, 0xcf, 0xdf,
	0x5f, 0xd5, 0x36, 0x02, 0xbd, 0x01, 0x7a, 0x4f, 0xd0, 0x57, 0xb8, 0x63, 0x5c, 0x34, 0xf4, 0x87,
	0x7b, 0xc2, 0xb1, 0xdf, 0xb6, 0x75, 0x35, 0x61, 0xb8, 0xb6, 0xe6, 0xde, 0x43, 0xa8, 0xe4, 0xba,
	0x9c, 0xf1, 0x3c, 0x0e, 0x32, 0x14, 0x43, 0xe7, 0xd8, 0x35, 0xf4, 0x64, 0xcf, 0x39, 0xeb, 0xbd,
	0xfd, 0xf4, 0x62, 0xde, 0x8c, 0x1b, 0xe8, 0x71, 0x7d, 0xdc, 0x3b, 0x18, 0xf7, 0x5d, 0x3d, 0xd1,
	0x8f, 0x37, 0x93, 0x2f, 0x4e, 0x44, 0xe5, 0x3a, 0x5f, 0x3a, 0x2b, 0x96, 0xb8, 0x5e, 0x3e, 0xe7,
	0xf4, 0x33, 0x89, 0xb3, 0x7c, 0xae, 0x3e, 0x8c, 0xb1, 0x2a, 0x1d, 0x17, 0xdb, 0xfa, 0xca, 0xcc,
	0x58, 0xde, 0xd6, 0x3f, 0x2f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x35, 0x47, 0x08, 0x40,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WordSearchClient is the client API for WordSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WordSearchClient interface {
	SingleWordSearch(ctx context.Context, in *SingleWordRequest, opts ...grpc.CallOption) (*SingleWordResponse, error)
	TopFiveSearch(ctx context.Context, in *TopFiveRequest, opts ...grpc.CallOption) (*TopFiveResponse, error)
	UpdateWordList(ctx context.Context, in *UpdateWordListRequest, opts ...grpc.CallOption) (*UpdateWordListResponse, error)
}

type wordSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewWordSearchClient(cc grpc.ClientConnInterface) WordSearchClient {
	return &wordSearchClient{cc}
}

func (c *wordSearchClient) SingleWordSearch(ctx context.Context, in *SingleWordRequest, opts ...grpc.CallOption) (*SingleWordResponse, error) {
	out := new(SingleWordResponse)
	err := c.cc.Invoke(ctx, "/wsproto.WordSearch/SingleWordSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordSearchClient) TopFiveSearch(ctx context.Context, in *TopFiveRequest, opts ...grpc.CallOption) (*TopFiveResponse, error) {
	out := new(TopFiveResponse)
	err := c.cc.Invoke(ctx, "/wsproto.WordSearch/TopFiveSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordSearchClient) UpdateWordList(ctx context.Context, in *UpdateWordListRequest, opts ...grpc.CallOption) (*UpdateWordListResponse, error) {
	out := new(UpdateWordListResponse)
	err := c.cc.Invoke(ctx, "/wsproto.WordSearch/UpdateWordList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordSearchServer is the server API for WordSearch service.
type WordSearchServer interface {
	SingleWordSearch(context.Context, *SingleWordRequest) (*SingleWordResponse, error)
	TopFiveSearch(context.Context, *TopFiveRequest) (*TopFiveResponse, error)
	UpdateWordList(context.Context, *UpdateWordListRequest) (*UpdateWordListResponse, error)
}

// UnimplementedWordSearchServer can be embedded to have forward compatible implementations.
type UnimplementedWordSearchServer struct {
}

func (*UnimplementedWordSearchServer) SingleWordSearch(ctx context.Context, req *SingleWordRequest) (*SingleWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleWordSearch not implemented")
}
func (*UnimplementedWordSearchServer) TopFiveSearch(ctx context.Context, req *TopFiveRequest) (*TopFiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopFiveSearch not implemented")
}
func (*UnimplementedWordSearchServer) UpdateWordList(ctx context.Context, req *UpdateWordListRequest) (*UpdateWordListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWordList not implemented")
}

func RegisterWordSearchServer(s *grpc.Server, srv WordSearchServer) {
	s.RegisterService(&_WordSearch_serviceDesc, srv)
}

func _WordSearch_SingleWordSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordSearchServer).SingleWordSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wsproto.WordSearch/SingleWordSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordSearchServer).SingleWordSearch(ctx, req.(*SingleWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordSearch_TopFiveSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopFiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordSearchServer).TopFiveSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wsproto.WordSearch/TopFiveSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordSearchServer).TopFiveSearch(ctx, req.(*TopFiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordSearch_UpdateWordList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWordListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordSearchServer).UpdateWordList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wsproto.WordSearch/UpdateWordList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordSearchServer).UpdateWordList(ctx, req.(*UpdateWordListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WordSearch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wsproto.WordSearch",
	HandlerType: (*WordSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SingleWordSearch",
			Handler:    _WordSearch_SingleWordSearch_Handler,
		},
		{
			MethodName: "TopFiveSearch",
			Handler:    _WordSearch_TopFiveSearch_Handler,
		},
		{
			MethodName: "UpdateWordList",
			Handler:    _WordSearch_UpdateWordList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/moqwordsearch.proto",
}
